#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

remove_repo_secret_copy() {
  local name="$1" names
  if ! names="$(gh secret list --repo "$REPO_SLUG" --json name --jq '.[].name')"; then
    warn "cannot inspect repository-scoped secrets; refusing to install a deployment secret"
    return 1
  fi
  if grep -Fxq "$name" <<< "$names"; then
    gh secret delete "$name" --repo "$REPO_SLUG" >/dev/null
  fi
  if ! names="$(gh secret list --repo "$REPO_SLUG" --json name --jq '.[].name')"; then
    warn "cannot verify repository-scoped secret deletion"
    return 1
  fi
  if grep -Fxq "$name" <<< "$names"; then
    warn "REPOSITORY_SECRET_COPY_STILL_PRESENT: $name"
    return 1
  fi
}

remove_repo_variable_copy() {
  local name="$1" names
  if ! names="$(gh variable list --repo "$REPO_SLUG" --json name --jq '.[].name')"; then
    warn "cannot inspect repository-scoped variables; refusing to install a deployment variable"
    return 1
  fi
  if grep -Fxq "$name" <<< "$names"; then
    gh variable delete "$name" --repo "$REPO_SLUG" >/dev/null
  fi
  if ! names="$(gh variable list --repo "$REPO_SLUG" --json name --jq '.[].name')"; then
    warn "cannot verify repository-scoped variable deletion"
    return 1
  fi
  if grep -Fxq "$name" <<< "$names"; then
    warn "REPOSITORY_VARIABLE_COPY_STILL_PRESENT: $name"
    return 1
  fi
}

# set_secret NAME VALUE — set a GitHub Actions environment secret via gh.
# An identically named repository secret is a hard failure, not a fallback.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    remove_repo_secret_copy "$name" || exit 1
    if printf '%s' "$value" | gh secret set "$name" --env "$GITHUB_ENVIRONMENT" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub environment secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub environment secret $name (set it manually with --env $GITHUB_ENVIRONMENT)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    remove_repo_variable_copy "$name" || exit 1
    if gh variable set "$name" --env "$GITHUB_ENVIRONMENT" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub environment variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
REPO_SLUG="asqatqazet/AI-Assisted-Review-Generation"
GITHUB_ENVIRONMENT="student"
FAILED_MIGRATION="20260823000019_operator_capability_rls"

banner "Resume student deployment from Neon"

stage "Recover and finish the Neon migrations"
say "This resumes the original setup at Stage 4; AWS and OIDC setup will not run again."
for command_name in git gh node pnpm; do
  command -v "$command_name" >/dev/null 2>&1 || {
    warn "$command_name is required before continuing"
    exit 1
  }
done
gh auth status >/dev/null 2>&1 || {
  warn "Run gh auth login before continuing."
  exit 1
}
CURRENT_REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
[[ "$CURRENT_REPO" == "$REPO_SLUG" ]] || {
  warn "Expected $REPO_SLUG, got $CURRENT_REPO"
  exit 1
}
open_url "https://console.neon.tech/"
step "If the owner URL was pasted into chat or logs, reset that role's password first."
step "Open Connect, disable connection pooling, select the owner role, and copy the rotated direct TLS URL."
if ! confirm "Has the exposed Neon owner password been rotated?"; then
  warn "Recovery stops until the exposed credential is rotated."
  exit 1
fi
ask_secret NEON_MIGRATION_DATABASE_URL "Paste the rotated direct migration-owner URL:"
until DATABASE_URL_TO_CHECK="$NEON_MIGRATION_DATABASE_URL" node scripts/validate-neon-database-url.mjs; do
  warn "Expected a direct Neon PostgreSQL URL, not a pooled or malformed URL."
  warn "The rejected value was not printed or stored. Paste the URL again."
  NEON_MIGRATION_DATABASE_URL=""
  printf '  %s%s%s ' "$BOLD" "Paste the rotated direct migration-owner URL:" "$RESET"
  if ! read -rs NEON_MIGRATION_DATABASE_URL; then
    printf '\n'
    warn "No database URL was read. Re-run this recovery wizard when it is ready."
    exit 1
  fi
  printf '\n'
done

MIGRATION_OUTPUT=$(mktemp)
cleanup_migration_output() { rm -f "$MIGRATION_OUTPUT"; }
trap cleanup_migration_output EXIT
if DATABASE_URL="$NEON_MIGRATION_DATABASE_URL" \
  pnpm --dir packages/db exec prisma migrate deploy --schema prisma/schema.prisma \
  >"$MIGRATION_OUTPUT" 2>&1; then
  say "All committed migrations are already applied."
else
  FAILED_NAMES=$(grep -Eo '20[0-9]{12}_[a-z0-9_]+' "$MIGRATION_OUTPUT" | sort -u | paste -sd ' ' - || true)
  if ! grep -Fq "P3009" "$MIGRATION_OUTPUT" || [[ "$FAILED_NAMES" != "$FAILED_MIGRATION" ]]; then
    warn "UNEXPECTED_FAILED_MIGRATION: refusing to mark any migration rolled back."
    warn "The Prisma failure was not the one recovery this wizard is allowed to repair."
    sed -E 's#postgres(ql)?://[^[:space:]]+#<redacted-database-url>#g' "$MIGRATION_OUTPUT" >&2
    exit 1
  fi
  warn "Neon contains the known partial migration: $FAILED_MIGRATION"
  if ! confirm "Mark only this failed migration rolled back and replay it?"; then
    warn "No migration state was changed."
    exit 1
  fi
  DATABASE_URL="$NEON_MIGRATION_DATABASE_URL" \
    pnpm --dir packages/db exec prisma migrate resolve \
    --rolled-back "$FAILED_MIGRATION" \
    --schema prisma/schema.prisma
  DATABASE_URL="$NEON_MIGRATION_DATABASE_URL" \
    pnpm --dir packages/db exec prisma migrate deploy \
    --schema prisma/schema.prisma
fi
cleanup_migration_output
trap - EXIT
set_secret NEON_MIGRATION_DATABASE_URL "$NEON_MIGRATION_DATABASE_URL"

stage "Create isolated reviewer, Console and Generation connections"
random_hex() {
  node -e 'process.stdout.write(require("node:crypto").randomBytes(Number(process.argv[1])).toString("hex"))' "$1"
}

CONTEXT_RUNTIME_DB_PASSWORD=$(random_hex 24)
CONSOLE_CONTROL_DB_PASSWORD=$(random_hex 24)
GENERATION_DB_PASSWORD=$(random_hex 24)
printf "ALTER ROLE context_runtime_svc PASSWORD '%s'; ALTER ROLE console_control_svc PASSWORD '%s'; ALTER ROLE generation_svc PASSWORD '%s';" \
  "$CONTEXT_RUNTIME_DB_PASSWORD" "$CONSOLE_CONTROL_DB_PASSWORD" "$GENERATION_DB_PASSWORD" |
  DATABASE_URL="$NEON_MIGRATION_DATABASE_URL" pnpm --dir packages/db exec prisma db execute --schema prisma/schema.prisma --stdin

pooled_url() {
  DATABASE_URL_BASE="$NEON_MIGRATION_DATABASE_URL" RUNTIME_USER="$1" RUNTIME_PASSWORD="$2" node -e '
    const url = new URL(process.env.DATABASE_URL_BASE);
    const labels = url.hostname.split(".");
    if (!labels[0].endsWith("-pooler")) labels[0] += "-pooler";
    url.hostname = labels.join(".");
    url.username = process.env.RUNTIME_USER;
    url.password = process.env.RUNTIME_PASSWORD;
    url.searchParams.set("sslmode", "require");
    process.stdout.write(url.toString());
  '
}

NEON_CONTEXT_RUNTIME_DATABASE_URL=$(pooled_url context_runtime_svc "$CONTEXT_RUNTIME_DB_PASSWORD")
NEON_CONSOLE_CONTROL_DATABASE_URL=$(pooled_url console_control_svc "$CONSOLE_CONTROL_DB_PASSWORD")
NEON_GENERATION_DATABASE_URL=$(pooled_url generation_svc "$GENERATION_DB_PASSWORD")
printf 'SELECT 1;' | DATABASE_URL="$NEON_CONTEXT_RUNTIME_DATABASE_URL" pnpm --dir packages/db exec prisma db execute --schema prisma/schema.prisma --stdin
printf 'SELECT 1;' | DATABASE_URL="$NEON_CONSOLE_CONTROL_DATABASE_URL" pnpm --dir packages/db exec prisma db execute --schema prisma/schema.prisma --stdin
printf 'SELECT 1;' | DATABASE_URL="$NEON_GENERATION_DATABASE_URL" pnpm --dir packages/db exec prisma db execute --schema prisma/schema.prisma --stdin
set_secret NEON_CONTEXT_RUNTIME_DATABASE_URL "$NEON_CONTEXT_RUNTIME_DATABASE_URL"
set_secret NEON_CONSOLE_CONTROL_DATABASE_URL "$NEON_CONSOLE_CONTROL_DATABASE_URL"
set_secret NEON_GENERATION_DATABASE_URL "$NEON_GENERATION_DATABASE_URL"
say "All three service-role connections authenticated; no runtime receives the owner URL."

stage "Generate application signing material"
KEY_DIRECTORY=$(mktemp -d)
chmod 700 "$KEY_DIRECTORY"
cleanup_keys() { rm -rf "$KEY_DIRECTORY"; }
trap cleanup_keys EXIT
KEY_DIRECTORY="$KEY_DIRECTORY" node --input-type=module -e '
  import { generateKeyPairSync } from "node:crypto";
  import { writeFileSync } from "node:fs";
  for (const name of ["context", "console-authority", "generation"]) {
    const { privateKey, publicKey } = generateKeyPairSync("ed25519");
    writeFileSync(
      `${process.env.KEY_DIRECTORY}/${name}-private.pem`,
      privateKey.export({ format: "pem", type: "pkcs8" }),
      { mode: 0o600 },
    );
    writeFileSync(
      `${process.env.KEY_DIRECTORY}/${name}-public.pem`,
      publicKey.export({ format: "pem", type: "spki" }),
      { mode: 0o600 },
    );
  }
'
set_secret CONTEXT_WORK_PRIVATE_KEY_PEM "$(<"$KEY_DIRECTORY/context-private.pem")"
set_secret CONTEXT_WORK_PUBLIC_KEY_PEM "$(<"$KEY_DIRECTORY/context-public.pem")"
set_secret CONSOLE_AUTHORITY_PRIVATE_KEY_PEM "$(<"$KEY_DIRECTORY/console-authority-private.pem")"
set_secret CONSOLE_AUTHORITY_PUBLIC_KEY_PEM "$(<"$KEY_DIRECTORY/console-authority-public.pem")"
set_secret CONSOLE_DATABASE_AUTHORITY_SECRET "$(random_hex 32)"
set_secret GENERATION_WORK_PRIVATE_KEY_PEM "$(<"$KEY_DIRECTORY/generation-private.pem")"
set_secret GENERATION_WORK_PUBLIC_KEY_PEM "$(<"$KEY_DIRECTORY/generation-public.pem")"
set_secret REVIEW_CSRF_SECRET "$(random_hex 32)"
set_secret PUBLIC_SOURCE_RATE_HMAC_SECRET "$(random_hex 32)"
cleanup_keys
trap - EXIT
say "The private keys were sent to GitHub and removed from the temporary directory."

stage "Review configuration and open the deploy workflow"
say "Expected student-environment variables:"
gh variable list --env "$GITHUB_ENVIRONMENT" | grep -E '^(AWS_DEPLOY_ROLE_ARN|COST_ALERT_EMAIL)[[:space:]]' || true
say "Expected student-environment secrets (GitHub never reveals their values):"
gh secret list --env "$GITHUB_ENVIRONMENT" | grep -E '^(NEON_MIGRATION_DATABASE_URL|NEON_CONTEXT_RUNTIME_DATABASE_URL|NEON_CONSOLE_CONTROL_DATABASE_URL|NEON_GENERATION_DATABASE_URL|REVIEW_CSRF_SECRET|PUBLIC_SOURCE_RATE_HMAC_SECRET|CONTEXT_WORK_PRIVATE_KEY_PEM|CONTEXT_WORK_PUBLIC_KEY_PEM|CONSOLE_AUTHORITY_PRIVATE_KEY_PEM|CONSOLE_AUTHORITY_PUBLIC_KEY_PEM|CONSOLE_DATABASE_AUTHORITY_SECRET|GENERATION_WORK_PRIVATE_KEY_PEM|GENERATION_WORK_PUBLIC_KEY_PEM)[[:space:]]' || true
open_url "https://github.com/$REPO_SLUG/actions/workflows/deploy-student.yml"
step "Choose Run workflow on main."
step "Enter a teardown date before the AWS Free-plan expiry."
step "Keep student-low-quota, leave the provider-cost acknowledgement false, and require every step to pass."
warn "Do not enable a paid model or put real customer/reviewer data into this assessment deployment."

finish
