#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

remove_repo_secret_copy() {
  local name="$1" names
  if ! names="$(gh secret list --repo "$REPO_SLUG" --json name --jq '.[].name')"; then
    warn "cannot inspect repository-scoped secrets; refusing to install a deployment secret"
    return 1
  fi
  if grep -Fxq "$name" <<< "$names"; then
    gh secret delete "$name" --repo "$REPO_SLUG" >/dev/null
  fi
  if ! names="$(gh secret list --repo "$REPO_SLUG" --json name --jq '.[].name')"; then
    warn "cannot verify repository-scoped secret deletion"
    return 1
  fi
  if grep -Fxq "$name" <<< "$names"; then
    warn "REPOSITORY_SECRET_COPY_STILL_PRESENT: $name"
    return 1
  fi
}

remove_repo_variable_copy() {
  local name="$1" names
  if ! names="$(gh variable list --repo "$REPO_SLUG" --json name --jq '.[].name')"; then
    warn "cannot inspect repository-scoped variables; refusing to install a deployment variable"
    return 1
  fi
  if grep -Fxq "$name" <<< "$names"; then
    gh variable delete "$name" --repo "$REPO_SLUG" >/dev/null
  fi
  if ! names="$(gh variable list --repo "$REPO_SLUG" --json name --jq '.[].name')"; then
    warn "cannot verify repository-scoped variable deletion"
    return 1
  fi
  if grep -Fxq "$name" <<< "$names"; then
    warn "REPOSITORY_VARIABLE_COPY_STILL_PRESENT: $name"
    return 1
  fi
}

# set_secret NAME VALUE — set a GitHub Actions environment secret via gh.
# An identically named repository secret is a hard failure, not a fallback.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    remove_repo_secret_copy "$name" || exit 1
    if printf '%s' "$value" | gh secret set "$name" --env "$GITHUB_ENVIRONMENT" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub environment secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub environment secret $name (set it manually with --env $GITHUB_ENVIRONMENT)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    remove_repo_variable_copy "$name" || exit 1
    if gh variable set "$name" --env "$GITHUB_ENVIRONMENT" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub environment variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
REPO_SLUG="asqatqazet/AI-Assisted-Review-Generation"
GITHUB_ENVIRONMENT="student"
IMMUTABLE_OIDC_SUBJECT="repo:asqatqazet@79821148/AI-Assisted-Review-Generation@1336406804:environment:student"
PERMISSIONS_BOUNDARY_NAME="ReviewStudentLambdaBoundary"

banner "Student AWS deployment setup"

stage "Local and GitHub prerequisites"
say "Run this wizard from the repository root. It stores cloud secrets only in GitHub."
for command_name in git gh node pnpm openssl; do
  command -v "$command_name" >/dev/null 2>&1 || {
    warn "$command_name is required before continuing"
    exit 1
  }
done
gh auth status >/dev/null 2>&1 || {
  open_url "https://cli.github.com/manual/gh_auth_login"
  warn "Run: gh auth login"
  exit 1
}
CURRENT_REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
[[ "$CURRENT_REPO" == "$REPO_SLUG" ]] || {
  warn "Expected $REPO_SLUG, got $CURRENT_REPO"
  exit 1
}
say "GitHub CLI is authenticated for $CURRENT_REPO."
pause "Continue to the account security gate?"

stage "Revoke the exposed AWS root key"
say "The root key pasted in the project conversation must be treated as compromised."
open_url "https://console.aws.amazon.com/iam/home#/security_credentials"
step "Sign in as the AWS account root user only for this security task."
step "Open Access keys, deactivate the exposed key, then permanently delete it."
step "Enable root MFA and review CloudTrail Event history for unfamiliar activity."
if ! confirm "Is the exposed root key deleted and root MFA enabled?"; then
  warn "Deployment setup stops until this security gate is complete."
  exit 1
fi

stage "Create the GitHub OIDC deployment role"
say "Use an IAM Identity Center administrator for this and later AWS administration."
open_url "https://console.aws.amazon.com/iam/home#/identity_providers"
step "Add an OpenID Connect provider with URL https://token.actions.githubusercontent.com"
step "Set its audience to sts.amazonaws.com. Reuse the existing provider if it already exists."
open_url "https://console.aws.amazon.com/iam/home#/roles/create"
step "Create a Web identity role for the GitHub provider; use owner asqatqazet, repository AI-Assisted-Review-Generation, branch main."
step "Name it review-github-deploy-student and attach PowerUserAccess in this dedicated student account."
ask AWS_ACCOUNT_ID "Enter the 12-digit AWS account ID:"
[[ "$AWS_ACCOUNT_ID" =~ ^[0-9]{12}$ ]] || {
  warn "AWS account ID must contain exactly 12 digits."
  exit 1
}
say "After creation, edit the role Trust relationships policy to use this exact immutable subject:"
note "$IMMUTABLE_OIDC_SUBJECT"
say "The two StringEquals conditions must be aud=sts.amazonaws.com and sub=$IMMUTABLE_OIDC_SUBJECT."
say "Create the customer-managed permissions boundary $PERMISSIONS_BOUNDARY_NAME first:"
cat <<BOUNDARY
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "StudentLambdaLogs",
        "Effect": "Allow",
        "Action": ["logs:CreateLogStream", "logs:PutLogEvents"],
        "Resource": "arn:aws:logs:eu-central-1:$AWS_ACCOUNT_ID:log-group:/aws/lambda/review-*-student:*"
      },
      {
        "Sid": "StudentRuntimeParameters",
        "Effect": "Allow",
        "Action": "ssm:GetParameter",
        "Resource": "arn:aws:ssm:eu-central-1:$AWS_ACCOUNT_ID:parameter/review-gen/student/*"
      },
      {
        "Sid": "StudentServiceInvocation",
        "Effect": "Allow",
        "Action": "lambda:InvokeFunction",
        "Resource": "arn:aws:lambda:eu-central-1:$AWS_ACCOUNT_ID:function:review-*-student:*"
      }
    ]
  }
BOUNDARY
step "In IAM Policies, create that policy with the exact name $PERMISSIONS_BOUNDARY_NAME."
say "Add an inline IAM policy allowing only the five exact bounded Lambda roles to be managed and passed:"
cat <<POLICY
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "CreateOnlyBoundedStudentLambdaRoles",
        "Effect": "Allow",
        "Action": ["iam:CreateRole", "iam:PutRolePermissionsBoundary"],
        "Resource": [
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-web-bff-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-context-service-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-context-reviewer-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-context-console-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-generation-service-student-role"
        ],
        "Condition": {
          "ArnEquals": {
            "iam:PermissionsBoundary": "arn:aws:iam::$AWS_ACCOUNT_ID:policy/$PERMISSIONS_BOUNDARY_NAME"
          }
        }
      },
      {
        "Sid": "ManageExactStudentLambdaRoles",
        "Effect": "Allow",
        "Action": [
          "iam:GetRole", "iam:DeleteRole",
          "iam:UpdateAssumeRolePolicy", "iam:TagRole", "iam:UntagRole",
          "iam:PutRolePolicy", "iam:GetRolePolicy", "iam:DeleteRolePolicy",
          "iam:ListRolePolicies", "iam:ListAttachedRolePolicies",
          "iam:ListInstanceProfilesForRole", "iam:ListRoleTags"
        ],
        "Resource": [
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-web-bff-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-context-service-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-context-reviewer-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-context-console-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-generation-service-student-role"
        ]
      },
      {
        "Effect": "Allow",
        "Action": "iam:PassRole",
        "Resource": [
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-web-bff-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-context-service-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-context-reviewer-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-context-console-student-role",
          "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-generation-service-student-role"
        ],
        "Condition": {"StringEquals": {"iam:PassedToService": "lambda.amazonaws.com"}}
      }
    ]
  }
POLICY
pause "Create that inline policy, then press Enter."
ask AWS_DEPLOY_ROLE_ARN "Paste the deployment role ARN:"
[[ "$AWS_DEPLOY_ROLE_ARN" == "arn:aws:iam::$AWS_ACCOUNT_ID:role/review-github-deploy-student" ]] || {
  warn "Role ARN does not match the expected account and role name."
  exit 1
}
ask COST_ALERT_EMAIL "Enter the email that will actively monitor AWS cost alerts:"
[[ "$COST_ALERT_EMAIL" == *@*.* ]] || {
  warn "Enter a valid monitored email address."
  exit 1
}
open_url "https://github.com/$REPO_SLUG/settings/environments"
step "Create the environment named student."
step "Under Deployment branches and tags choose Selected branches and tags, then allow only main."
if ! confirm "Is the student environment restricted to main?"; then
  warn "OIDC deployment stops until the student environment is branch-protected."
  exit 1
fi
# A paid-provider key is optional and not collected by this zero-cost wizard,
# but a repository-scoped copy would still be visible to an environment job.
remove_repo_secret_copy GEMINI_API_KEY || exit 1
set_var AWS_DEPLOY_ROLE_ARN "$AWS_DEPLOY_ROLE_ARN"
set_var COST_ALERT_EMAIL "$COST_ALERT_EMAIL"

stage "Create the Neon Free database"
open_url "https://console.neon.tech/"
step "Create one Free project in Frankfurt and keep its synthetic assessment data only."
step "Open Connect, disable connection pooling, select the owner role, and copy the direct TLS URL."
ask_secret NEON_MIGRATION_DATABASE_URL "Paste the direct migration-owner URL:"
if ! DATABASE_URL_TO_CHECK="$NEON_MIGRATION_DATABASE_URL" node -e '
  const url = new URL(process.env.DATABASE_URL_TO_CHECK);
  if (!url.protocol.startsWith("postgres") || !url.hostname.endsWith("neon.tech") || url.hostname.includes("-pooler")) process.exit(1);
'; then
  warn "Expected a direct Neon PostgreSQL URL, not a pooled URL."
  exit 1
fi
if ! confirm "Apply the committed migrations to this new Neon database?"; then
  warn "Runtime roles do not exist until the migrations are applied."
  exit 1
fi
DATABASE_URL="$NEON_MIGRATION_DATABASE_URL" pnpm --dir packages/db exec prisma migrate deploy --schema prisma/schema.prisma
set_secret NEON_MIGRATION_DATABASE_URL "$NEON_MIGRATION_DATABASE_URL"

stage "Create isolated reviewer, Console and Generation connections"
CONTEXT_RUNTIME_DB_PASSWORD=$(openssl rand -hex 24)
CONSOLE_CONTROL_DB_PASSWORD=$(openssl rand -hex 24)
GENERATION_DB_PASSWORD=$(openssl rand -hex 24)
printf "ALTER ROLE context_runtime_svc PASSWORD '%s'; ALTER ROLE console_control_svc PASSWORD '%s'; ALTER ROLE generation_svc PASSWORD '%s';" \
  "$CONTEXT_RUNTIME_DB_PASSWORD" "$CONSOLE_CONTROL_DB_PASSWORD" "$GENERATION_DB_PASSWORD" |
  DATABASE_URL="$NEON_MIGRATION_DATABASE_URL" pnpm --dir packages/db exec prisma db execute --schema prisma/schema.prisma --stdin

pooled_url() {
  DATABASE_URL_BASE="$NEON_MIGRATION_DATABASE_URL" RUNTIME_USER="$1" RUNTIME_PASSWORD="$2" node -e '
    const url = new URL(process.env.DATABASE_URL_BASE);
    const labels = url.hostname.split(".");
    if (!labels[0].endsWith("-pooler")) labels[0] += "-pooler";
    url.hostname = labels.join(".");
    url.username = process.env.RUNTIME_USER;
    url.password = process.env.RUNTIME_PASSWORD;
    url.searchParams.set("sslmode", "require");
    process.stdout.write(url.toString());
  '
}

NEON_CONTEXT_RUNTIME_DATABASE_URL=$(pooled_url context_runtime_svc "$CONTEXT_RUNTIME_DB_PASSWORD")
NEON_CONSOLE_CONTROL_DATABASE_URL=$(pooled_url console_control_svc "$CONSOLE_CONTROL_DB_PASSWORD")
NEON_GENERATION_DATABASE_URL=$(pooled_url generation_svc "$GENERATION_DB_PASSWORD")
printf 'SELECT 1;' | DATABASE_URL="$NEON_CONTEXT_RUNTIME_DATABASE_URL" pnpm --dir packages/db exec prisma db execute --schema prisma/schema.prisma --stdin
printf 'SELECT 1;' | DATABASE_URL="$NEON_CONSOLE_CONTROL_DATABASE_URL" pnpm --dir packages/db exec prisma db execute --schema prisma/schema.prisma --stdin
printf 'SELECT 1;' | DATABASE_URL="$NEON_GENERATION_DATABASE_URL" pnpm --dir packages/db exec prisma db execute --schema prisma/schema.prisma --stdin
set_secret NEON_CONTEXT_RUNTIME_DATABASE_URL "$NEON_CONTEXT_RUNTIME_DATABASE_URL"
set_secret NEON_CONSOLE_CONTROL_DATABASE_URL "$NEON_CONSOLE_CONTROL_DATABASE_URL"
set_secret NEON_GENERATION_DATABASE_URL "$NEON_GENERATION_DATABASE_URL"
say "All three service-role connections authenticated; no runtime receives the owner URL."

stage "Generate application signing material"
KEY_DIRECTORY=$(mktemp -d)
chmod 700 "$KEY_DIRECTORY"
cleanup_keys() { rm -rf "$KEY_DIRECTORY"; }
trap cleanup_keys EXIT
openssl genpkey -algorithm ED25519 -out "$KEY_DIRECTORY/context-private.pem" >/dev/null 2>&1
openssl pkey -in "$KEY_DIRECTORY/context-private.pem" -pubout -out "$KEY_DIRECTORY/context-public.pem" >/dev/null 2>&1
openssl genpkey -algorithm ED25519 -out "$KEY_DIRECTORY/console-authority-private.pem" >/dev/null 2>&1
openssl pkey -in "$KEY_DIRECTORY/console-authority-private.pem" -pubout -out "$KEY_DIRECTORY/console-authority-public.pem" >/dev/null 2>&1
openssl genpkey -algorithm ED25519 -out "$KEY_DIRECTORY/generation-private.pem" >/dev/null 2>&1
openssl pkey -in "$KEY_DIRECTORY/generation-private.pem" -pubout -out "$KEY_DIRECTORY/generation-public.pem" >/dev/null 2>&1
set_secret CONTEXT_WORK_PRIVATE_KEY_PEM "$(<"$KEY_DIRECTORY/context-private.pem")"
set_secret CONTEXT_WORK_PUBLIC_KEY_PEM "$(<"$KEY_DIRECTORY/context-public.pem")"
set_secret CONSOLE_AUTHORITY_PRIVATE_KEY_PEM "$(<"$KEY_DIRECTORY/console-authority-private.pem")"
set_secret CONSOLE_AUTHORITY_PUBLIC_KEY_PEM "$(<"$KEY_DIRECTORY/console-authority-public.pem")"
set_secret CONSOLE_DATABASE_AUTHORITY_SECRET "$(openssl rand -hex 32)"
set_secret GENERATION_WORK_PRIVATE_KEY_PEM "$(<"$KEY_DIRECTORY/generation-private.pem")"
set_secret GENERATION_WORK_PUBLIC_KEY_PEM "$(<"$KEY_DIRECTORY/generation-public.pem")"
set_secret REVIEW_CSRF_SECRET "$(openssl rand -hex 32)"
set_secret PUBLIC_SOURCE_RATE_HMAC_SECRET "$(openssl rand -hex 32)"
cleanup_keys
trap - EXIT
say "The private keys were sent to GitHub and removed from the temporary directory."

stage "Review configuration and open the deploy workflow"
say "Expected student-environment variables:"
gh variable list --env "$GITHUB_ENVIRONMENT" | grep -E '^(AWS_DEPLOY_ROLE_ARN|COST_ALERT_EMAIL)[[:space:]]' || true
say "Expected student-environment secrets (GitHub never reveals their values):"
gh secret list --env "$GITHUB_ENVIRONMENT" | grep -E '^(NEON_MIGRATION_DATABASE_URL|NEON_CONTEXT_RUNTIME_DATABASE_URL|NEON_CONSOLE_CONTROL_DATABASE_URL|NEON_GENERATION_DATABASE_URL|REVIEW_CSRF_SECRET|PUBLIC_SOURCE_RATE_HMAC_SECRET|CONTEXT_WORK_PRIVATE_KEY_PEM|CONTEXT_WORK_PUBLIC_KEY_PEM|CONSOLE_AUTHORITY_PRIVATE_KEY_PEM|CONSOLE_AUTHORITY_PUBLIC_KEY_PEM|CONSOLE_DATABASE_AUTHORITY_SECRET|GENERATION_WORK_PRIVATE_KEY_PEM|GENERATION_WORK_PUBLIC_KEY_PEM)[[:space:]]' || true
open_url "https://github.com/$REPO_SLUG/actions/workflows/deploy-student.yml"
step "Choose Run workflow on main."
step "Enter a teardown date before the AWS Free-plan expiry."
step "Keep student-low-quota, leave the provider-cost acknowledgement false, and require every step to pass."
warn "Do not enable a paid model or put real customer/reviewer data into this assessment deployment."

finish
