import { useState } from "react";
import { Link } from "react-router-dom";

import type { ConsoleClient } from "../console-client.js";
import { useConsoleView } from "../console-queries.js";
import {
  DataTable,
  QueryState,
  ViewHeader,
  scopeLabel,
} from "../console-ui.js";
import styles from "../operator-console.module.css";
import type { ConsoleScopeController } from "../use-console-scope.js";

/**
 * Every venue's distribution assets in one place, so handing out links does not
 * mean opening each venue in turn.
 */
export function DistributionOverviewView({
  client,
  scopeController,
}: {
  readonly client: ConsoleClient;
  readonly scopeController: ConsoleScopeController;
}): React.JSX.Element {
  const overview = useConsoleView({
    client,
    view: "distribution-overview",
    scope: scopeController.scope,
  });
  const [copied, setCopied] = useState<string | null>(null);

  return (
    <>
      <ViewHeader
        eyebrow="Account"
        title="Distribution"
        meta={
          overview.data === undefined
            ? undefined
            : scopeLabel(overview.data.scope)
        }
      />
      <p className={styles.emptyCopy}>
        Each venue has its own link, so a review is attributed to the venue the
        reviewer actually visited. Print or send the one that belongs to it.
      </p>
      <QueryState query={overview} label="distribution" />
      {copied === null ? null : (
        <p role="status">Survey URL for {copied} copied.</p>
      )}

      {overview.data === undefined ? null : (
        <DataTable
          caption="Survey links and QR codes by venue"
          empty="This account has no Location yet, so there is nothing to hand out."
          rows={overview.data.locations}
          rowKey={(row) => row.locationId}
          columns={[
            {
              key: "name",
              header: "Venue",
              rowHeader: true,
              render: (row) => (
                <Link
                  to={scopeController.href(
                    `/console/locations/${row.locationId}/distribution`,
                    { locationId: row.locationId },
                  )}
                >
                  {row.name}
                </Link>
              ),
            },
            {
              key: "url",
              header: "Survey link",
              render: (row) => <span className={styles.mono}>{row.liveUrl}</span>,
            },
            {
              key: "entryMode",
              header: "Entry",
              render: (row) => (
                <>
                  {row.entryMode}
                  <p className={styles.settingSource}>
                    {row.verifiesVisit ? "visit verified" : "visit not verified"}
                  </p>
                </>
              ),
            },
            {
              key: "counters",
              header: "Issued / opened / completed",
              render: (row) =>
                `${row.counters.issued} / ${row.counters.opened} / ${row.counters.completed}`,
            },
            {
              key: "qr",
              header: "QR code",
              render: (row) =>
                row.qrSvg === null ? (
                  <span className={styles.settingSource}>
                    {row.qrUnavailableReason ?? "No QR code is available."}
                  </span>
                ) : (
                  <span
                    className={styles.qrThumbnail}
                    aria-label={`QR code for ${row.name}`}
                    // Generated by the server from this venue's real URL.
                    dangerouslySetInnerHTML={{ __html: row.qrSvg }}
                  />
                ),
            },
            {
              key: "actions",
              header: "",
              render: (row) => (
                <span className={styles.buttonRow}>
                  <button
                    type="button"
                    className={styles.button}
                    onClick={() => {
                      void navigator.clipboard
                        ?.writeText(row.liveUrl)
                        .then(() => setCopied(row.name))
                        .catch(() => setCopied(null));
                    }}
                  >
                    Copy link
                  </button>
                  {row.qrSvg === null ? null : (
                    <a
                      className={styles.button}
                      download={`survey-qr-${row.slug}.svg`}
                      href={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(row.qrSvg)}`}
                    >
                      Download QR
                    </a>
                  )}
                </span>
              ),
            },
          ]}
        />
      )}
    </>
  );
}
